# Generated by Django 3.2.14 on 2022-07-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category1',
            new_name='category',
        ),
    ]
